### ISSUE TITLE
Control-Backspace, Alt-Backspace not working after enabling ble.sh

### ISSUE THREAD

**Issue by banoris** [banoris/dotfiles#10]
See:

- <https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#311-representation-of-ret-esc-tab-bs-del-and-c-bs>
- <https://unix.stackexchange.com/questions/264791/ctrl-backspace-and-ctrl-delete-in-bash>

**Comment by akinomyoga** [comment]
FYI, I have received some issues in ble.sh and searched for related discussions before.

- https://github.com/akinomyoga/ble.sh/issues/94
- https://github.com/akinomyoga/ble.sh/issues/104
- https://github.com/msys2/MSYS2-packages/pull/2490
- https://github.com/microsoft/terminal/issues/755

I now again checked how each terminal behaves and summarized it in a new table in [ble.sh §3.1.1 "Representation of RET, ESC, TAB, BS, DEL, and C-BS"](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#311-representation-of-ret-esc-tab-bs-del-and-c-bs). I have been somehow thinking that the most terminal sends <kbd>C-?</kbd> and <kbd>C-_</kbd> for <kbd>Backspace</kbd> and <kbd>Ctrl+Backspace</kbd>, respectively, but it was my misunderstanding. Actually, the most terminal sends <kbd>C-h</kbd> for <kbd>Ctrl+Backspace</kbd>. However, interestingly, some terminal behaves in the completely opposite way.

**Comment by anprowh** [comment]
For those who will find this in the future: <kbd>Alt-h</kbd>
